### ISSUE TITLE
Different or customizable $loading property

### ISSUE THREAD

**Issue by cioraneanu** [f/vuex-loading#13]
I find this library extremely useful, but the used property name is causing problems for me.

For example I'm using it along with element-ui, which also defined a this.$loading field resulting in  errors.

In VueJS documentation, there is the recommendation of giving such field unique names:
https://vuejs.org/v2/style-guide/#Private-property-names-essential

It would be great if the exposed field could be defined in the constructor options, or renamed entirely to something else like $vuexLoading

**Comment by attx** [comment]
Any workaround for this?

**Comment by pooot** [comment]
I forked the repo and changed the value manually.
https://github.com/pooot/vuex-loading/commit/97db83135ec0c58e50e9ab5ec77fcbf273bd3645

**Comment by attx** [comment]
`this.$loading` with your fork is still element-ui´s `$loading`

**Comment by pooot** [comment]
Didn't modify the reference to $loading in v-loading.vue, fixed and pushed :) Should only be references to $vuexLoading now.

**Comment by f** [comment]
PR's are welcome.

**Comment by pooot** [comment]
I'll try and make it configurable and submit a PR :)
