### ISSUE TITLE
Add support of wildcards

### ISSUE THREAD

**Issue by Koc** [f/vuex-loading#16]
For example have 2 actions: `addProductToCart`, `refreshCart`. Each of they call `startLoading(dispatcher, 'cart')` on method enter and `endLoading(dispatcher, 'cart')` before each return. The problem occurs when `addProductToCart` calls `refreshCart` inside. End loading occurs too early.

It is similar to nested transactions.

**Comment by f** [comment]
Do not use same loading key for different actions. You should use `startLoading(d, 'adding product to card')` and `startLoading(d, 'refreshing cart')`. And you can watch `$loader.isLoading(['adding product to cart', 'refreshing cart'])` to wait both of loaders to be finished.

**Comment by Koc** [comment]
This can be sollution but not for all cases. For example we loading products

```js
startLoading(dispatcher, `products.${id}`)
```

and I should make check for any loading products: `$loader.isLoading('products.*')` but asterisk syntax not supported.

**Comment by f** [comment]
@Koc this looks nice.

**Comment by Koc** [comment]
covered by #31
