### ISSUE TITLE
make vuex optional

### ISSUE THREAD

**Issue by sky-code** [f/vuex-loading#4]
Hi there, your loader is best of this https://github.com/vuejs/awesome-vue#loader by api and features but require `vuex`. Can you make `vuex` optional for people who use it, and provide all features by plugin itself without `vuex` store?
I can help with that if you want.

**Comment by f** [comment]
That looks like a good idea. I have not enough time to do it but PR's welcome :) I'm waiting for your PR! 👍

**Comment by f** [comment]
Actually decoupling it from Vuex makes sense but also Vuex is useful when you use Vuex Debugger. So we may want to make the "vuex-less" version optional but not Vuex (technically same but politically different)

**Comment by sky-code** [comment]
By a flag `enableVuex` we can map all properties from store to `Vue` plugin otherwise use default `Vue` instance properties.
All data management must be moved in separate abstraction `storage`
for `enableVuex=false` for `storage` use `Vue` instance with `data` for properties
for `enableVuex=true` for `storage` use Vue` instance with `computed` properties that get/set data to `Vuex` store

**Comment by johnmerced** [comment]
This is now in the latest release. Could we close this?

**Comment by sky-code** [comment]
yes, this can be closed now
