### ISSUE TITLE
 [Vue warn]: You are using the runtime-only build of Vue

### ISSUE THREAD

**Issue by nkwinder** [f/vuex-loading#6]
Hello, 

I use .vue files for my components and webpack.
I tried to use v-loading component on my template, and i get this error at runtime: 

vue.runtime.esm.js:570 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available.

Any ideas?

thanks

**Comment by wooliet** [comment]
Try this:
https://github.com/vuejs-templates/webpack/issues/215#issuecomment-238095102

**Comment by f** [comment]
I do not think it's because of vuex-loading.
