### ISSUE TITLE
vuex-loading is undefined

### ISSUE THREAD

**Issue by lbineau** [f/vuex-loading#9]
The new version 0.2.5 seems to be broken.
```javascript
import VueLoading from 'vuex-loading'
console.log(VueLoading) // output undefined
```

**Comment by lbineau** [comment]
Latest working version: 0.2.2

**Comment by f** [comment]
It seems it's working. Can you approve you use 0.2.5?

**Comment by lbineau** [comment]
```

**Comment by lbineau** [comment]
It works until version 0.2.3. 
I'm using```yarn add vuex-loading@versionNumber``` to test.

**Comment by lbineau** [comment]
That is weird but as a workaround I used the source in my project 
```javascript
import VuexLoading from 'vuex-loading/src/vuex-loading'
```

**Comment by f** [comment]
That's strange, it's working to me.

26 Oca 2018 Cum 12:17 tarihinde lbineau <notifications@github.com> şunu
yazdı:
